version: "3.9"
services:
  api:
    build:
      context: ./backend
    image: api
    ports:
    - 8000:8000
    volumes:
      - ./backend:/api
    env_file:
      - ./backend/.env
  ui:
    build:
      context: ./frontend
    image: ui
    ports:
    - 3000:3000
    volumes:
      - ./frontend:/ui

