version: "3.9"
services:
  api:
    build:
      context: ./backend
    ports:
    - 8000:8000
    volumes:
      - ./backend:/api
    env_file:
      - ./backend/.env
  ui:
    build:
      context: ./frontend
    ports:
    - 7000:7000
    volumes:
      - ./frontend:/ui

